#!/usr/bin/env bash
INJMON_LOG_FILE=${INJMON_LOG_FILE:-/dev/stdout}
function monitor() {
    while :
    do
        sleep 10
        if [ "$INJ_CONDITION" != "" ]; then
            bash -c "$INJ_CONDITION"
            if [ "$?" = "0" ]; then
                echo "funtool is running."
                continue
            fi
            echo "funtool isn't running. starting..."
        fi
        inject-dll
    done
}
monitor
